Fix: use aref when fieldmapping is empty
Tools4everBV/HelloID-Conn-Prov-Target-GoodHabitz pull request #2
Opened 2024-12-03 10:39 UTC by rhouthuijzen

2025-01-02 11:38 UTC, Rick-Jongbloed requested changes
This is an interesting connector... :-) Please have a look at my comments and contact me if you have any questions

2025-01-02 11:38 UTC, Rick-Jongbloed commented on README.md
> +| update.ps1         | PowerShell _update_ lifecycle action |
I think it would be good to describe the actions you're executing in each script. Especially since the create and update scripts only do correlation. I know we have a bit disclaimer describing this, but it wouldn't hurt to repeat that message?

2025-01-02 11:38 UTC, Rick-Jongbloed commented on update.ps1
> +        $outputContext.AuditLogs.Add([PSCustomObject]@{
Do we want to do something with previousData so the audit message is only shown when previousdata != data?

2025-01-02 11:38 UTC, Rick-Jongbloed commented on delete.ps1
>          throw 'The account reference could not be found'
in the readme, you say: 'The $actionContext.References.Account is used when $actionContext.Data.EmailAddress is empty in the delete lifecycle action.' and in the mapping the aRef is will empty when there's no emailaddress. If there's a situation where the emailaddress is empty in aRef, the script will fail here, instead of getting the emailaddress from the mapping. The chance that this occurs is very slim, but i do think we should fix this. 

I think we can fix this by throwing an error only when aRef _and_ Data.EmailAddress are empty.

2025-01-02 11:38 UTC, Rick-Jongbloed commented on update.ps1
> +                Action  = 'CorrelateAccount'
We also say we correlate while Data.Emailaddress is empty?

2025-01-02 11:38 UTC, Rick-Jongbloed commented on update.ps1
> +                Action  = 'CorrelateAccount'
i think these comments apply to the create script too

2025-01-24 14:23 UTC, rhouthuijzen commented on update.ps1
> +        $outputContext.AuditLogs.Add([PSCustomObject]@{
Fixed by checking if we need to update aref

2025-01-24 14:24 UTC, rhouthuijzen commented on delete.ps1
>          throw 'The account reference could not be found'
The aRef can't be empty. The create/update script will fail. So this shouldn't matter

2025-01-24 14:25 UTC, rhouthuijzen commented on update.ps1
> +                Action  = 'CorrelateAccount'
Fixed by checking if there is a value else throwing the script. Generating a better to understand error (like Topdesk)

2025-01-24 14:25 UTC, merged